<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->insert([
            [
            'name' => 'iPhone 11 Pro',
            'sku' => '',
            'image' => 'https://www.apple.com/v/iphone/home/am/images/overview/compare/compare_iphone_11_pro__fvqwhr4dkhiu_large.jpg',
            'category' => '1',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => '999',
            'discount_price' => '',
            'description' => 'Triple-camera system (Ultra Wide, Wide, Telephoto)Up to 20 hours of video playback1Water resistant to a depth of 4 meters for up to 30 minutes25.8” or 6.5” Super Retina XDR display3',
            'rate' => '0'
            ], 
            [
            'name' => ' iPhone 11 ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/iphone/home/am/images/overview/compare/compare_iphone_11__f0r1z5etd722_large.jpg ',
            'category' => '1',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 699 ',
            'discount_price' => '',
            'description' => ' Dual-camera system (Ultra Wide, Wide)Up to 17 hours of video playback1Water resistant to a depth of 2 meters for up to 30 minutes26.1” Liquid Retina HD display3 ',
            'rate' => '0'
            ], 
            [
            'name' => ' iPhone SE ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/iphone/home/am/images/overview/compare/compare_iphone_se__buv6h7jbk5n6_large.jpg ',
            'category' => '1',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 399 ',
            'discount_price' => '',
            'description' => ' Single-camera system(Wide)Up to 13 hours of video playback1Water resistant to a depth of 1 meter for up to 30 minutes24.7” Retina HD display ',
            'rate' => '0'
            ], 
            [
            'name' => ' iPhone X ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/iphone/home/am/images/overview/compare/compare_iphone_xr__dexbg7jerlqq_large.jpg ',
            'category' => '1',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 599 ',
            'discount_price' => '',
            'description' => ' Single-camera system(Wide)Up to 16 hours of video playback1Water resistant to a depth of 1 meter for up to 30 minutes26.1” Liquid Retina HD display3 ',
            'rate' => '0'
            ], 
            [
            'name' => ' MacBook Air ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/mac/home/at/images/overview/compare/macbook_air__bfz9o93hnyuq_medium.jpg ',
            'category' => '2',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 999  ',
            'discount_price' => '',
            'description' => ' 13.3-inch Retina display1Up to 4-core Intel Core i7 processorUp to 16GB memoryUp to 2TB storage2Up to 11 hours battery life3Touch IDBacklit Magic Keyboard ',
            'rate' => '0'
            ], 
            [
            'name' => ' MacBook Pro 13 ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/mac/home/at/images/overview/compare/macbook_pro_13__ft1pc3lqwd6y_medium.jpg ',
            'category' => '2',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 1299  ',
            'discount_price' => '',
            'description' => ' 13.3-inch Retina display1Up to 4-core Intel Core i7 processorUp to 32GB memoryUp to 4TB storage2Up to 10 hours battery life3Touch Bar and Touch IDBacklit Magic Keyboard ',
            'rate' => '0'
            ], 
            [
            'name' => ' MacBook Pro 16 ',
            'sku' => '',
            'image' => ' https://www.apple.com/v/mac/home/at/images/overview/compare/macbook_pro_16__x90efpvdutu6_medium.jpg ',
            'category' => '2',
            'type' => '',
            'brand' => '1',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 2399  ',
            'discount_price' => '',
            'description' => ' 16-inch Retina display1Up to 8-core Intel Core i9 processorUp to 64GB memoryUp to 8TB storage2Up to 11 hours battery life3Touch Bar and Touch IDBacklit Magic Keyboard ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI P40 Pro ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/phones/p40-pro/main-product/positive.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 999  ',
            'discount_price' => '',
            'description' => ' Ultra Vision Leica Quad Camera, 1/1.28 inch SensorKirin 990 5G90 Hz Display, IP68 ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI P40 ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/p40/p40-silver.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 990  ',
            'discount_price' => '',
            'description' => ' Ultra Vision Leica Triple Camera, 1/1.28 inch SensorKirin 990 5GAI Portrait, HUAWEI Golden Snap ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI P40 Pro+ ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/p40-pro-plus/p40-pro-plus-white.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 799  ',
            'discount_price' => '',
            'description' => ' Ultra Vision Leica Penta Camera, 1/1.28 inch Sensor10x Optical Zoom, 100x Max ZoomNano Ceramic, 90 Hz Display, IP68 ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI Mate Xs ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/phones/mate-x-s/matexs-plp.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 599  ',
            'discount_price' => '',
            'description' => ' 8" Foldable FullView DisplayRevolutionary Multitasking Interactive ExperienceKirin 990 5G SoC ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI Mate 30 Pro 5G ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/mate30-pro-5g/mate30-pro-orange.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 800  ',
            'discount_price' => '',
            'description' => ' Kirin 990 5G ChipsetSuperSensing Cine Camera for videography4500 mAh Battery, 40W HUAWEI SuperCharge ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI Mate 30 Pro ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/mate30-pro-4g/mate30-pro-cosmic-purple.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 700  ',
            'discount_price' => '',
            'description' => ' HUAWEI Horizon DisplaySuperSensing Cine Camera for videography4500 mAh Battery, 40W HUAWEI SuperCharge ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI Mate 30 5G ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/mate30-5g/mate30-orange.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 600  ',
            'discount_price' => '',
            'description' => ' Kirin 990 5G Chipset4200 mAh Battery, 40W HUAWEI SuperChargeGesture Control, EMUI10 ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI Mate 30 ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/mate30-4g/mate30-cosmic-purple.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 489  ',
            'discount_price' => '',
            'description' => ' Kirin 990, HUAWEI SuperChargeSuperSensing Triple CameraGesture Control, EMUI10 ',
            'rate' => '0'
            ], 
            [
            'name' => ' PORSCHE DESIGN HUAWEI Mate 30 RS ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/list-image/phones/porsche-design-mate30-rs/pd-mate30-rs-black.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 499  ',
            'discount_price' => '',
            'description' => ' Kirin 990 5G ChipsetUltra-curved OLED Display, Genuine LeatherLeica Quad Camera, HUAWEI SuperCharge ',
            'rate' => '0'
            ], 
            [
            'name' => ' HUAWEI P30 Pro ',
            'sku' => '',
            'image' => ' https://consumer.huawei.com/content/dam/huawei-cbg-site/en/mkt/pdp/phones/p30-pro/list-image/p30-pro-blue.png ',
            'category' => '1',
            'type' => '',
            'brand' => '2',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 599  ',
            'discount_price' => '',
            'description' => ' 6.47’’ OLED display, IP68Leica Quad Camera, SuperZoom Lens, Super Spectrum SensorHUAWEI 40 W SuperCharge ',
            'rate' => '0'
            ], 
            [
            'name' => ' Galaxy A01 Core ',
            'sku' => '',
            'image' => ' https://www.samsung.com/th/smartphones/galaxy-a01core-a013/SM-A013GZKGTHL/ ',
            'category' => '1',
            'type' => '',
            'brand' => '3',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 800  ',
            'discount_price' => '',
            'description' => '     จอใหญ่ เปิดมุมมองการรับชมที่ดีกว่าดีไซน์เครื่องบาง อัดแน่นเต็มประสิทธิภาพมากกว่าเคยออกแบบมา เพื่อประสิทธิภาพการใช้งานที่ดีสุด ',
            'rate' => '0'
            ], 
            [
            'name' => ' Galaxy Note20 Ultra ',
            'sku' => '',
            'image' => ' https://images.samsung.com/is/image/samsung/th/galaxy-note20/gallery/th-galaxy-note20-ultra-n985-sm-n985fzngthl-frontmysticbronze-thumb-272422126?$PF_PRD_PNG$ ',
            'category' => '1',
            'type' => '',
            'brand' => '3',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 799  ',
            'discount_price' => '',
            'description' => ' 1. เลือกรับส่วนลด Galaxy Buds Live 50%2. เลือกรับส่วนลด 3,000.- สำหรับลูกค้าใหม่ เพียงใส่โค้ด"POWERPHONE"พร้อมบริการ Samsung Care+ นาน 1 ปี คลิก21-31 ส.ค. 63หน่วยประมวลผลที่ดีขึ้นเพื่อสมรรถนะที่สูงกว่าเดิมให้ความรู้สึกราวกับปากกาจริงด้วยความหน่วงที่ต่ำ ',
            'rate' => '0'
            ], 
            [
            'name' => ' Galaxy Note20 ',
            'sku' => '',
            'image' => ' https://images.samsung.com/is/image/samsung/th/galaxy-note20/gallery/th-galaxy-note20-n980-sm-n980fzggthl-frontmysticgreen-thumb-272432048?$PF_PRD_PNG$ ',
            'category' => '1',
            'type' => '',
            'brand' => '3',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 599  ',
            'discount_price' => '',
            'description' => ' 1. เลือกรับส่วนลด Galaxy Buds Live 50%2. เลือกรับส่วนลด 2,000.- สำหรับลูกค้าใหม่ เพียงใส่โค้ด"POWERPHONE"พร้อมบริการ Samsung Care+ นาน 1 ปี คลิก21-31 ส.ค. 63หน่วยประมวลผลที่ดีขึ้นเพื่อสมรรถนะที่สูงกว่าเดิมให้ความรู้สึกราวกับปากกาจริงด้วยความหน่วงที่ต่ำ ',
            'rate' => '0'
            ], 
            [
            'name' => ' Galaxy Note20 Ultra 5G ',
            'sku' => '',
            'image' => ' https://images.samsung.com/is/image/samsung/th/galaxy-note20/gallery/th-galaxy-note20-ultra-5g-n986-sm-n986bznwthl-frontmysticbronze-thumb-272432879?$PF_PRD_PNG$ ',
            'category' => '1',
            'type' => '',
            'brand' => '3',
            'stock' => '10',
            'color' => '',
            'weight' => '',
            'ragular_price' => ' 599  ',
            'discount_price' => '',
            'description' => ' 1. เลือกรับส่วนลด Galaxy Buds Live 50%2. เลือกรับส่วนลด 3,000.- สำหรับลูกค้าใหม่ เพียงใส่โค้ด"POWERPHONE"พร้อมบริการ Samsung Care+ นาน 1 ปี คลิก21-31 ส.ค. 63หน่วยประมวลผลที่ดีขึ้นเพื่อสมรรถนะที่สูงกว่าเดิ ',
            'rate' => '0'
            ], 
        ]);
    }
}
